config/routes.rb
Rails.application.routes.draw do
  get 'tweets/index'

  get 'tweets/show'

  get 'users/index'
  get 'users/:id' => 'users#show'
  get 'users' => 'users#index'

  get 'tweets/:id/edit' => 'tweets#edit'
  get 'tweets/new' => 'tweets#new'
  post 'tweets/:id' => 'tweets#update'
  post 'tweets' => 'tweets#create'
  get 'tweets/:id' => 'tweets#show'
  get 'tweets' => 'tweets#index'

  root 'tweets#index'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user


  validates :body, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tweets

  validates :handle, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @page = params[:page] || "1"
    if params[:search].nil?
      @tweets = get_tweets
    else
      @tweets = get_tweets_by_search
    end
  end

  def show
    @tweet = get_tweet_at_id
  end

  def new
    @error = params[:error]
  end

  def create
    if params[:body].nil? || params[:body].empty?
      redirect_to "/tweets/new?error=true"
    else
      user = User.first
      Tweet.create(body: params[:body], user_id: user.id)
      redirect_to "/"
    end
  end

  def edit
    @tweet = get_tweet_at_id
    @error = params[:error]
  end

  def update
    if params[:body].nil? || params[:body].empty?
      redirect_to "/tweets/new?error=true"
    else
      @tweet = get_tweet_at_id
      @tweet.body = params[:body]
      @tweet.save
      redirect_to "/tweets/#{@tweet.id}"
    end
  end

  def destroy

  end

  private

  def get_tweet_at_id
    Tweet.find_by(id: params[:id].to_i)
  end

  def get_tweets
    Tweet.order(updated_at: :desc).limit(25).offset((@page.to_i - 1)*25)
  end

  def get_tweets_by_search
    Tweet.where("body LIKE '%#{params[:search]}%'").order(updated_at: :desc).limit(25).offset((@page.to_i - 1)*25)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @page = params[:page] || "1"
    if params[:search].nil?
      @users = get_users
    else
      @users = get_users_by_search
    end
  end

  def show
    @page = params[:page] || "1"
    @user = get_user_at_id
    if params[:search].nil?
      @tweets = @user.tweets.order(updated_at: :desc).limit(25).offset((@page.to_i - 1)*25)
    else
      @tweets = @user.tweets.where("body LIKE '%#{params[:search]}%'").order(updated_at: :desc).limit(25).offset((@page.to_i - 1)*25)
    end
  end

  def new

  end

  def create

  end

  def edit

  end

  def update

  end

  private

  def get_user_at_id
    User.find_by(id: params[:id].to_i)
  end

  def get_users
    User.limit(25).offset((@page.to_i - 1)*25)
  end

  def get_users_by_search
    User.where("first_name LIKE '%#{params[:search]}%'").limit(25).offset((@page.to_i - 1)*25)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitterapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="nav">
    <ul>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Users", users_path %></li>
    <li><%= link_to "New Tweet", tweets_new_path %></li>
    </ul>
  </nav>
<form method='get'>
<label for='search'>Search:</label>
        <input name='search' type='search'/>
        <input type='submit'/>
</form>
<%= yield %>

</body>
</html>

app/views/tweets/edit.html.erb
<h1> hi there </h1>
<% if @error %>
<h3> Invalid Input </h3>
<% end %>
<form action='/tweets/<%= @tweet.id %>' method="post" accept-charset="utf-8" id='update-tweet'>
  <label for='body'>Tweet</label>
    <textarea name='body' id='body'><%= @tweet.body %></textarea>
  <input type='submit' name='commit' id='update_tweet'  />
</form>

app/views/tweets/index.html.erb
<h1>Tweets#index</h1>
<p>Find me in app/views/tweets/index.html.erb</p>
<% @tweets.each do |tweet| %>
<p><a href="/users/<%= tweet.user.id %>">$<%= tweet.user.handle %></a>:
    <%= tweet.updated_at.strftime('%x') %> at <%= tweet.updated_at.strftime('%r') %></p>
<p><a href="/tweets/<%= tweet.id %>" style="text-decoration:none;color:black;">
    <%= tweet.body %></a> </p>
      <br>
<% end %>
<ul>
  <% unless @page.to_i <= 1 %>
    <li> <a href="/tweets?page=<%= @page.to_i - 1%>"> Previous </a></li>
  <% end %>
  <% unless @page.to_i * 25 >= Tweet.count  %>
    <li> <a href="/tweets?page=<%= @page.to_i + 1%>"> Next </a></li>
  <% end %>
</ul>

app/views/tweets/new.html.erb
<h1> hi there </h1>
<% if @error %>
<h3> Invalid Input </h3>
<% end %>
<form action='/tweets' method="post" accept-charset="utf-8" id='new-tweet'>
  <label for='body'>Tweet</label>
    <textarea name='body' id='body'></textarea>
  <input type='submit' name='commit' id='create_tweet'  />
</form>

app/views/tweets/show.html.erb
<h1>Tweets#show</h1>
<p>Find me in app/views/tweets/show.html.erb</p>
<h1><a href="/users/<%= @tweet.user.id %>">$<%= @tweet.user.handle %></a>
    <small><%= @tweet.updated_at.strftime('%x') %> at <%= @tweet.updated_at.strftime('%r') %>
    </small></h1>
<h3> Tweet </h3>
<p><a href="/tweets/<%= @tweet.id %>/edit"> Edit </a></p>
<p><%= @tweet.body %></p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>
<% @users.each do |user| %>
<p><a href="/users/<%= user.id %>">$<%= user.handle %></a>:
    <%= user.first_name %> <%= user.last_name %></p>
<% end %>
<ul>
  <% unless @page.to_i <= 1 %>
    <li> <a href="/users?page=<%= @page.to_i - 1%>"> Previous </a></li>
  <% end %>
  <% unless @page.to_i * 25 >= User.count  %>
    <li> <a href="/users?page=<%= @page.to_i + 1%>"> Next </a></li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<h1><a href="/users/<%= @user.id %>">$<%= @user.handle %></a></h1>
<h3>Name: <%= @user.first_name %> <%= @user.last_name %></h3>
<h3> Tweets </h3>
<% @tweets.each do |tweet| %>
<p><%= tweet.updated_at.strftime('%x') %> at <%= tweet.updated_at.strftime('%r') %></p>
<p> <a href="/tweets/<%= tweet.id %>" style="text-decoration:none;color:black;">
  <%= tweet.body %></a> </p>
  <br>
<% end %>
<ul>
  <% unless @page.to_i <= 1 %>
    <li> <a href="/users/<%= @user.id %>?page=<%= @page.to_i - 1%>"> Previous </a></li>
  <% end %>
  <% unless @page.to_i * 25 >= @user.tweets.count  %>
    <li> <a href="/users/<%= @user.id %>?page=<%= @page.to_i + 1%>"> Next </a></li>
  <% end %>
</ul>